name: 功能建议
description: 提出功能建议
body:
  - type: markdown
    attributes:
      value: |
        请提供详细的描述方便寻找到您反映的问题。
  - type: input
    id: version
    attributes:
      label: 使用的版本
      description: 请输入您所使用的的程序版本。
      placeholder: 例如：1.0.1
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: 平台
      description: 请输入您的平台。
      placeholder: 例如：Windows 7 专业版 x64
    validations:
      required: false
  - type: textarea
    id: bug-report
    attributes:
      label: 更详细的描述
      description: 请尽可能地详细描述问题，比如此功能的用途。

